# Lab 8 - A Dot product and a Matrix Multiplication in PyTorch and Tensorflow

Using PyTorch: 
  * Calculate the dot product between two vectors each of length 3 
  * Calculate the matrix multiplication of two 2-dimensional matrices, each with a size of (2,2) 



In [3]:
# Using PyTorch
import torch
import sys
import torch
import helpers as h

In [6]:
# defining two vectors of length 3
vectorA = torch.tensor([8.0, 8.0, 9.0])
vectorB = torch.tensor([3.0, 9.0, 9.0])


In [8]:
h.print_tensor_info(vectorA)
h.print_tensor_info(vectorB)

tensor([8., 8., 9.])
Type         <class 'torch.Tensor'>
dtype        torch.float32
Dimension    1
Shape        (3,)
tensor([3., 9., 9.])
Type         <class 'torch.Tensor'>
dtype        torch.float32
Dimension    1
Shape        (3,)


In [20]:
# Calculating the dot product
dot_productA = vectorA.dot(vectorB)
dot_productB = vectorB.dot(vectorA)




In [21]:
# Printing the result
print("Dot Product of A and B:", dot_productA)
print("Dot Product of B and A:", dot_productB)



Dot Product of A and B: tensor(177.)
Dot Product of B and A: tensor(177.)


dot product of A and B is equal to dot product of B and A.

In [16]:
A = torch.tensor([[4., 1.],[1., 6.]])
B = torch.tensor([[4., 3.],[8., 8.]])

print(A)
print(B)

tensor([[4., 1.],
        [1., 6.]])
tensor([[4., 3.],
        [8., 8.]])


In [19]:
# performing matrix multiplication 
matmul = torch.matmul(A, B)
print("Matrix multiplication A and B  : ", matmul)

Matrix multiplication A and B  :  tensor([[24., 20.],
        [52., 51.]])


In [18]:
# matrix multiplication of B, A
matmulBA = B.matmul(A)
print(" Matrix multiplication of B and A is ",matmulBA)

 Matrix multiplication of B and A is  tensor([[19., 22.],
        [40., 56.]])


Matrix multiplication of A and B is not equal to matrix multiplication of B and A